"""app/prompts/__init__.py"""
from app.prompts.system_prompt import MASTER_SYSTEM_PROMPT, ORCHESTRATOR_SYSTEM_PROMPT
from app.prompts.planner_prompt import PLANNER_SYSTEM_PROMPT, PLANNER_HUMAN_PROMPT
from app.prompts.writer_prompt import WRITER_SYSTEM_PROMPT, WRITER_HUMAN_PROMPT
from app.prompts.reviewer_prompt import REVIEWER_SYSTEM_PROMPT, REVIEWER_HUMAN_PROMPT
from app.prompts.agent_prompts import (
    FLIGHT_AGENT_SYSTEM_PROMPT,
    HOTEL_AGENT_SYSTEM_PROMPT,
    WEATHER_AGENT_SYSTEM_PROMPT,
    BUDGET_AGENT_SYSTEM_PROMPT,
    RESTAURANT_AGENT_SYSTEM_PROMPT,
    VISA_AGENT_SYSTEM_PROMPT,
    CURRENCY_AGENT_SYSTEM_PROMPT,
    WRITER_AGENT_SYSTEM_PROMPT,
)

__all__ = [
    "MASTER_SYSTEM_PROMPT",
    "ORCHESTRATOR_SYSTEM_PROMPT",
    "PLANNER_SYSTEM_PROMPT",
    "PLANNER_HUMAN_PROMPT",
    "WRITER_SYSTEM_PROMPT",
    "WRITER_HUMAN_PROMPT",
    "REVIEWER_SYSTEM_PROMPT",
    "REVIEWER_HUMAN_PROMPT",
    "FLIGHT_AGENT_SYSTEM_PROMPT",
    "HOTEL_AGENT_SYSTEM_PROMPT",
    "WEATHER_AGENT_SYSTEM_PROMPT",
    "BUDGET_AGENT_SYSTEM_PROMPT",
    "RESTAURANT_AGENT_SYSTEM_PROMPT",
    "VISA_AGENT_SYSTEM_PROMPT",
    "CURRENCY_AGENT_SYSTEM_PROMPT",
    "WRITER_AGENT_SYSTEM_PROMPT",
]
